/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ClientsIndexLazyImport = createFileRoute('/clients/')()
const ClientsClientIdLazyImport = createFileRoute('/clients/$clientId')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ClientsIndexLazyRoute = ClientsIndexLazyImport.update({
  path: '/clients/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/clients/index.lazy').then((d) => d.Route))

const ClientsClientIdLazyRoute = ClientsClientIdLazyImport.update({
  path: '/clients/$clientId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/clients/$clientId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/clients/$clientId': {
      preLoaderRoute: typeof ClientsClientIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/clients/': {
      preLoaderRoute: typeof ClientsIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ClientsClientIdLazyRoute,
  ClientsIndexLazyRoute,
])

/* prettier-ignore-end */
